project:
  type: website
  execute-dir: project
  preview: 
    browser: true
  render:
    # Same order as pages show on website. Make sure they run in right order
    - pages/index.qmd
    - pages/overview.qmd
    - pages/refine_economics.qmd
    - pages/refine_environment.qmd
    - pages/refine_production.qmd
    - pages/metadata_table.qmd
    - pages/metrics_table.qmd
    - pages/refined_framework.qmd
    - pages/refined_metadata.qmd
    - pages/metric_distributions.qmd
    - pages/aggregation.qmd
    - pages/indicator_distributions.qmd
    - pages/comparison.qmd
    - pages/indicator_correlations.qmd
    - pages/validation.qmd
    - pages/sensitivity.qmd
    - temp/test_notebook.ipynb
    - temp/test_python.qmd
    - temp/test_python_and_r.qmd
    - temp/bambi.ipynb
    - pages/frontiers_intro.qmd
    - pages/frontiers_trends.qmd
    - pages/bnlearn.qmd

website:
  title: "Food Systems Research Institute"
  reader-mode: false
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  repo-url: https://github.com/Food-Systems-Research-Institute/sm-docs
  navbar:
    logo: images/FSRI-SpiritMarks_FSRI-mark-white.png
    logo-href: https://www.uvm.edu/cals/food-systems-research
    search: true
    tools:
      - icon: tree
        menu:
          - text: FSRI
            href: https://www.uvm.edu/cals/food-systems-research
          - text: UVM
            href: https://www.uvm.edu
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/Food-Systems-Research-Institute/sm-docs
          - text: FSRI GitHub
            href: https://github.com/Food-Systems-Research-Institute
  sidebar:
    title: "Table of Contents"
    style: "docked"
    contents:
      - text: Home
        href: pages/index.qmd
      - text: Overview
        href: pages/overview.qmd
      - section: Indicator Refinement
        contents: 
          - text: Economics
            href: pages/refine_economics.qmd
          - text: Environment
            href: pages/refine_environment.qmd
          - text: Production
            href: pages/refine_production.qmd
      - section: Secondary Data
        contents:
          - text: Metadata
            href: pages/metadata_table.qmd
          - text: Metrics Data
            href: pages/metrics_table.qmd
      - section: Analysis
        contents:
          - text: Refined Framework
            href: pages/refined_framework.qmd
          - text: Refined Metadata
            href: pages/refined_metadata.qmd
          - text: Metric Distributions
            href: pages/metric_distributions.qmd
          - text: Aggregation
            href: pages/aggregation.qmd
          - text: Indicator Distributions
            href: pages/indicator_distributions.qmd
          - text: Comparisons
            href: pages/comparison.qmd
          - text: Indicator Correlations
            href: pages/indicator_correlations.qmd
          - text: Validation
            href: pages/validation.qmd
          - text: Sensitivity and Uncertainty 
            href: pages/sensitivity.qmd
      - section: Frontiers
        contents:
          - text: Intro
            href: pages/frontiers_intro.qmd
          - text: Trends
            href: pages/frontiers_trends.qmd
      - section: Testing
        contents:
          - text: Python .ipynb
            href: temp/test_notebook.ipynb
          - text: Python .qmd
            href: temp/test_python.qmd
          - text: Python and R .qmd
            href: temp/test_python_and_r.qmd
          - text: bambi.qmd
            href: temp/bambi.ipynb
          - text: bnlearn
            href: pages/bnlearn.qmd
          

format:
  html:
    page-layout: article 
    theme: custom_theme.scss # modified sandstone
    fig-align: left
    css: styles.css
    toc: true
    toc-title: "On This Page"
    toc-location: right
    toc-depth: 4
    number-sections: true
    number-depth: 4
    code-fold: true
    grid: 
      body-width: 900px
      sidebar-width: 250px
      margin-width: 250px
    mainfont: Roboto
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: true
    title-block-style: default

bibliography: fsrc.bib

execute:
  warning: false
  cache: true
  freeze: auto

editor_options:
  chunk_output_type: console