---
title: "Correlations"
format:
  html:
    fig-dpi: 200
    code-fold: true
editor_options: 
  chunk_output_type: console
warnings: false
execute:
  cache: false
---

```{r}
#| label: prep
#| cache: false
#| output: false
options(scipen = 999)

pacman::p_load(
  dplyr,
  htmltools,
  stringr,
  tidyr,
  reactable,
  purrr,
  broom,
  knitr,
  kableExtra,
  ggplot2,
  ggpubr,
  psych,
  tibble,
  Hmisc,
  reshape2,
  viridisLite,
  conflicted,
  readr,
  ggtext,
  snakecase
)

# GitHub packages
pacman::p_load_current_gh(
  'ChrisDonovan307/projecter',
  'Food-Systems-Research-Institute/SMdata'
)

# SMdocs project
devtools::load_all()

conflicts_prefer(
  dplyr::select(),
  dplyr::filter(),
  dplyr::pull(),
  dplyr::summarize(),
  stats::lag(),
  base::setdiff(),
  .quiet = TRUE
)
```

This page explores correlations among metrics across counties using the latest available time point for each metric.

## Wrangling

```{r}
#| label: wrangle
#| output: false
#| fig-height: 10
#| fig-width: 10
# metric crosswalk
crosswalk <- SMdocs::dp_meta %>% 
  select(variable_name, metric)

# Get df ready
get_str(SMdata::metrics)
df <- SMdata::metrics %>% 
  filter(variable_name %in% SMdocs::dp_meta$variable_name) %>% 
  SMdocs::get_latest_year() %>% 
  SMdata::filter_fips('new') %>% 
  mutate(variable_name = str_split_i(variable_name, '_', 1)) %>% 
  left_join(crosswalk) %>% 
  select(-variable_name) %>% 
  pivot_wider(
    id_cols = fips,
    values_from = value,
    names_from = metric
  )
get_str(df)

# Get an ordered framework from which we will pull metrics in alphabetical order
# and get the counts of metrics per dimension that we will use to draw lines
# between dimensions
get_str(dp_meta)
ordered_framework <- dp_meta %>% 
  arrange(dimension, metric) %>% 
  filter(metric %in% names(df))
ordered_framework
```

## Figure

```{r}
#| label: make_cor_table
#| output: false
# Get line placements to divide dimensions
# Reverse them to match alphabetical order of dimensions top to bottom
# Get cumulative sums to space them out across graph
# Then add 0.5 to each to put them in between cells
line_placements <- ordered_framework %>% 
  group_by(dimension) %>% 
  summarize(count = n()) %>% 
  pull(count) %>% 
  rev() %>% 
  cumsum() %>% 
  {. + 0.5}
line_placements

# Reorder our df in proper metric order
metric_order <- ordered_framework %>% 
  pull(metric)
df <- df %>% 
  select(fips, any_of(metric_order)) %>% 
  select(rev(everything()))
get_str(df)

# Create matrix of values
mat <- df %>% 
  na.omit() %>% 
  select(-fips) %>% 
  as.matrix()

# Get correlations
cor <- rcorr(mat, type = 'pearson')

# Melt correlation values and rename columns
cor_r <- reshape::melt(cor$r) %>% 
  setNames(c('var_1', 'var_2', 'value'))

# Save p values
cor_p <- melt(cor$P)
p.value <- cor_p$value

# Color code by dimension
# dimension_colors <- c(
#   "economics"  = "#BF7417FF",
#   "environment"  = "#A8BE74FF",
#   "health" = "#9CB6A9FF",
#   "production" = "#635C72FF",
#   "social" = "#784116FF"
# )

# Pasting dimension colors to metrics
colored_labels <- ordered_framework %>%
  mutate(
    label = paste0(
      "<span style='color:", dp_palette[dimension], "'>", to_title_case(str_replace_all(metric, "_", " ")), "</span>"
    )
  ) %>%
  select(metric, label) %>%
  deframe()

# Dummy data frame for dimension legend
dimension_legend_df <- tibble(
  x = -Inf,
  y = -Inf,
  dimension = factor(names(dp_palette), levels = names(dp_palette))
)

# Make heatmap
corplot <- ggplot(cor_r, aes(x = var_1, y = var_2, fill = value)) +
  geom_tile() + 
  
  geom_point(
    data = dimension_legend_df,
    aes(x = x, y = y, color = dimension),
    shape = 15,
    size = 5,
    inherit.aes = FALSE,
    show.legend = TRUE,
    alpha = 0  # fully transparent points, so they don't show up
  ) +
  
  scale_fill_gradient2(
    low = "#762a83", 
    mid = "white", 
    high = "#1b7837", 
    midpoint = 0,
    name = "Correlation"
  ) +
  scale_color_manual(
    values = dp_palette,
    labels = str_to_title(names(dp_palette)),
    name = "Dimension"
  ) +
  
  # Legend overrides
  guides(
    color = guide_legend(
      override.aes = list(shape = 15, size = 5, alpha = 1),
      nrow = 2
    )
  ) +
  
  # line placements
  geom_hline(yintercept = line_placements[1]) +
  geom_hline(yintercept = line_placements[2]) +
  geom_hline(yintercept = line_placements[3]) +
  geom_hline(yintercept = line_placements[4]) +
  geom_vline(xintercept = line_placements[1]) +
  geom_vline(xintercept = line_placements[2]) +
  geom_vline(xintercept = line_placements[3]) +
  geom_vline(xintercept = line_placements[4]) +
  scale_x_discrete(labels = colored_labels) +
  scale_y_discrete(labels = colored_labels) +
  
  theme(
    axis.text.x = element_markdown(angle = 45, hjust = 1),
    axis.text.y = element_markdown(),
    axis.text = element_text(family = "Times New Roman"),
    axis.title = element_blank(),
    plot.title = element_text(hjust = 0),
    legend.position = "top",
    legend.title.position = "top",
    legend.title = element_text(size = 10, family = "Times New Roman", hjust = 0.5),
    legend.text = element_text(size = 9, family = "Times New Roman"),
    legend.key = element_rect(fill = "transparent", colour = NA),
    legend.background = element_rect(fill = "transparent", colour = NA)
  )

ggsave(
  plot = corplot,
  filename = 'outputs/fig_corplot.png',
  height = 9,
  width = 9,
  # dpi = 300
)
```

```{r}
#| label: show_cor_table
#| echo: false
#| fig-height: 9
#| fig-width: 9
corplot
```

## Table

Large and unwieldy correlation matrix. Added another interactive one below that is probably easier to work with.

```{r}
#| label: latex_table
# Latex table
df <- cor$r %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column('var') %>% 
  mutate(var = str_sub(var, end = 6)) %>% 
  setNames(c(names(.) %>% str_sub(end = 6)))
  
df %>% 
  kbl(
    digits = 3, 
    format = "latex",
    caption = 'Correlation matrix of metrics using latest available time point',
    label = 'tab_correlations',
    booktabs = TRUE
    # longtable = TRUE
  ) %>%
  kable_styling(
    font_size = 5,
    bootstrap_options = c(
      "condensed"
    )
  ) %>% 
  save_kable(
    file = 'outputs/tab_correlations.tex'
  )

# HTML for website
cor$r %>% 
  kbl(
    digits = 3, 
    format = "html"
  ) %>%
  column_spec(1, width = '500px') %>% 
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c(
      "striped", 
      "hover", 
      "condensed"
    )
  )
```


## Long Table

Longer format table that is interactive and shows p values.

```{r}
#| label: cor_table_long
# Create long table with p values and stars
tab <- cor_r %>% 
  rename(cor = value) %>% 
  inner_join(cor_p, by = join_by(var_1 == Var1, var_2 == Var2)) %>% 
  rename(p = value) %>% 
  mutate(sig = ifelse(p < 0.05, '*', ''))

tab %>% 
  get_reactable(
    defaultColDef = colDef(
      format = colFormat(digits = 3)
    )
  )
```
